"""empty message

Revision ID: 6c5c83d86b52
Revises: 
Create Date: 2023-11-19 14:30:13.579757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c5c83d86b52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poke',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ability', sa.String(), nullable=False),
    sa.Column('attack_stat', sa.Integer(), nullable=False),
    sa.Column('hp_stat', sa.Integer(), nullable=False),
    sa.Column('defense_stat', sa.Integer(), nullable=False),
    sa.Column('sprite', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_poke',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('poke_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poke_id'], ['poke.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_poke')
    op.drop_table('poke')
    # ### end Alembic commands ###
