"""empty message

Revision ID: 8b2b585f8674
Revises: d05cf289ccde
Create Date: 2023-11-23 14:05:29.804408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b2b585f8674'
down_revision = 'd05cf289ccde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poke',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ability', sa.String(), nullable=False),
    sa.Column('attack_stat', sa.Integer(), nullable=False),
    sa.Column('hp_stat', sa.Integer(), nullable=False),
    sa.Column('defense_stat', sa.Integer(), nullable=False),
    sa.Column('sprite', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_poke', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'poke', ['poke_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_poke', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('poke')
    # ### end Alembic commands ###
