"""empty message

Revision ID: c08cf7341410
Revises: 6769b0c0528f
Create Date: 2023-11-18 19:31:58.254660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c08cf7341410'
down_revision = '6769b0c0528f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poke', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poke_added', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poke', schema=None) as batch_op:
        batch_op.drop_column('poke_added')

    # ### end Alembic commands ###
