"""empty message

Revision ID: d05cf289ccde
Revises: 6c5c83d86b52
Create Date: 2023-11-23 14:02:24.915333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd05cf289ccde'
down_revision = '6c5c83d86b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_poke',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('poke_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poke_id'], ['poke.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_poke')
    # ### end Alembic commands ###
